"""
State definition for the codebase analysis workflow.
Uses LangGraph's TypedDict for distributed state management across agents.
"""

import operator
from typing import Annotated, TypedDict
from pydantic import BaseModel, Field


class SubTask(BaseModel):
    """Individual research subtask extracted by the Planner."""

    task_id: str = Field(
        description="Unique identifier for this subtask (e.g., 'task_1', 'task_2')"
    )
    description: str = Field(
        description="Clear description of what to research (e.g., 'Find JWT validation logic')"
    )
    target_concept: str = Field(
        description="The key concept or file pattern to focus on (e.g., 'auth middleware', 'middleware/*.py')"
    )


class SubTaskList(BaseModel):
    """Container for the list of subtasks generated by the Planner."""

    security_related: bool = Field(
        default=False,
        description="Whether the user's query is specifically about code security or security vulnerabilities.",
    )
    tasks: list[SubTask] = Field(
        default_factory=list,
        description="List of decomposed security research subtasks. Empty if the query is not security-related or is too vague.",
    )


class ResearchState(TypedDict):
    """
    Complete state for a codebase research workflow.

    This TypedDict defines all information passed between LangGraph nodes:
    - Input: repo_path, query
    - Processing: subtasks, research_results, error_status
    - Output: final_report
    """

    repo_path: str
    """Local filesystem path to the cloned repository (e.g., /tmp/workspaces/job_123)."""

    query: str
    """The user's research question (e.g., 'Find JWT validation vulnerabilities')."""

    subtasks: list[dict]
    """
    List of research subtasks generated by the Planner.
    Each dict has keys: task_id, description, target_concept.
    Empty list if query is not security-related or is too vague.
    """

    research_results: Annotated[list[dict], operator.add]
    """
    Accumulated findings from researchers.
    Uses operator.add to support LangGraph's reducer pattern for appending results.
    Each dict contains: task_id, findings, file_citations (list of {path, line_range, snippet}).
    """

    final_report: str
    """
    Final Markdown-formatted report synthesized from all research_results.
    Includes exact file path and line-number citations.
    """

    error_status: str
    """Optional field for routing. Used to signal invalid input or other errors."""
